version: '3'
services:
  mod_perl-main:
    container_name: mod_perl-main
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      MYSQL_CONNECTION_STRING: "DBI:MariaDB:USER:IP_OR_FQDN_OF_MYSQL_OR_MARIADB"
      MYSQL_USER: "USER"
      MYSQL_PASSWORD: "PASS_FOR_USER"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./cgi-bin:/usr/local/apache2/cgi-bin
    ports:
      - "8080:80"
