version: '3'
services:
  mod_perl-main:
    container_name: mod_perl-main
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      ORACLE_CONNECTION_STRING: "dbi:Oracle:host=192.168.1.1;sid=SID.SIDDOM"
      ORACLE_USER: "USER"
      ORACLE_PASSWORD: "PASS_FOR_USER"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./cgi-bin:/usr/local/apache2/cgi-bin
    ports:
      - "18080:80"
